language: c
#language: objective-c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

#before_install:
# - apt-get install cmake mono-devel mono-gmcs
# - wget http://download.mono-project.com/archive/3.0.10/macos-10-x86/MonoFramework-MDK-3.0.10.macos10.xamarin.x86.dmg
# - hdid MonoFramework-MDK-3.0.10.macos10.xamarin.x86.dmg
# - installer -pkg "/Volumes/Mono Framework MDK 3.0.10/MonoFramework-MDK-3.0.10.macos10.xamarin.x86.pkg" -target /

branches:
 only:
   - master
   
env:
  - EnableNuGetPackageRestore=true

script:
  - .travis/PackageRestore.sh
  - xbuild src/HumbleNetwork.sln

notifications:
  email: false  