language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

branches:
 only:
   - master
   
env:
  - EnableNuGetPackageRestore=true

script:
  - .travis/PackageRestore.sh
  - xbuild src/HumbleNetwork.sln
  - nunit-console src/HumbleNetwork.Tests/bin/Debug/HumbleNetwork.Tests.dll

notifications:
  email: false  