using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.431
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.0.0.5")]
[assembly: AssemblyFileVersionAttribute("0.0.0.5")]
[assembly: AssemblyCopyrightAttribute("Copyright HumbleNetwork 2012")]
[assembly: AssemblyProductAttribute("HumbleNetwork")]
[assembly: AssemblyCompanyAttribute("HumbleNetwork")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.5")]

