using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18047
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2013.09.20.001")]
[assembly: AssemblyFileVersionAttribute("2013.09.20.001")]
[assembly: AssemblyCopyrightAttribute("Copyright Joao Carlos Clementoni 2013")]
[assembly: AssemblyProductAttribute("Humble Network")]
[assembly: AssemblyCompanyAttribute("Joao Carlos Clementoni")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("2013.09.20.001")]

